version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  # different jobs are calles later in the workflows sections
jobs:
  install-dep:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # install dependencies in both apps
      - run: |
            npm run frontend:install
      - run: |
            npm run backend:install
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - run: npm run frontend:build
      - run: npm run backend:build
workflows:
  install-workflow:
    jobs:
      - install-dep
      - build
